name: dart_cassandra_cql
version: 0.2.0
author: Achilleas Anagnostopoulos
description: Dart driver for apache Cassandra
homepage: https://github.com/achilleasa/dart_cassandra_cql
environment:
    sdk: ">=2.0.0 <3.0.0"
dependencies:
  uuid: ^1.0.3
  collection: ">=1.1.0 <2.0.0"
  logging: "^0.11.2"
dev_dependencies:
  test: ^1.0.0
